### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by wprl** [wprl/baucis#128]
Detect language and translate error messages, swagger, and other automatically generated text.  Accept-Language header?
##

**Comment by wprl** [comment]
This would be great, given the resources and/or community help.

**Comment by pjmolina** [comment]
Seems fair for `text/html` output for humans. 
But not needed for machine API consumption via `application/json`. In this second scenario unique error codes makes the trick and the client UI can do the i18n conversion when needed.

**Comment by wprl** [comment]
Mostly I'm thinking about error messages and any other text developers work with.

**Comment by pjmolina** [comment]
IMHO the majority of professional developers work and code in English, specially important if working in an international environment. Let's say for example if I start to name variables of functions using the letter eñe: `ñ` like in `enseñar` (_to teach_) any of you with non Spanish keyboard will start to have problems to type it (not to say to understand it). Same for accents and other language-specific characters. As a developer, I do not need i18n for error codes or code doc: English is the common interlingua here. I DO need i18n as a final user of an app in the UI layer.
