### ISSUE TITLE
How to Save Nested Documents

### ISSUE THREAD

**Issue by distracteddev** [wprl/baucis#134]
Mongoose Populate allows me to retrieve related documents, I was wondering what the best way would be to enable Baucis to be able to save related documents as well.
##

**Comment by wprl** [comment]
I'm thinking this could be best approached with HAL.  _embedded will contain any populated fields, which can be easily found by unique _id.  Then, one could POST/PUT with content-type of application/hal+json and baucis would loop through the _embedded documents creating/updating each.
