### ISSUE TITLE
Investigate use of lean option

### ISSUE THREAD

**Issue by wprl** [wprl/baucis#140]
Probably bypasses validation but may be useful in certain circumstances.
##

**Comment by wprl** [comment]
Do this along side more extensive perf testing.

**Comment by swordfish444** [comment]
@wprl Any updates to this feature?

**Comment by wprl** [comment]
The big feature for 2.0.0 is to decouple baucis from express and mongoose.  From talks with users, it appears that the best solution for this is to add support for the mongo client directly, and to deprecate the mongoose back end eventually.  Work has started on 2.x, but for the initial release mongoose will still be the only back end.

So, basically, the issue is being addressed in the long term.  However, for the short term, have you tried setting `request.baucis.query.lean(true)` somewhere in your code?  I’ve been meaning to see how well this works.  If you wouldn’t mind trying out that or a similar solution and letting me know how it goes, I’d be happy to help patch 1.x to support anything missing from this feature within the timeframe of the next couple weeks.

Cheers,
William

William Riley-Land / Principal & Open Source Consultant 
 <http://kun.io/>william@kun.io <mailto:william@kun.io>
Kun.io Labs 
http://kun.io <http://kun.io/>

**Comment by wprl** [comment]
v2 uses Mongo directly, not Mongoose.  That will accomplish the goals outlined in this issue.
