### ISSUE TITLE
Support for Koa

### ISSUE THREAD

**Issue by brycejacobs** [wprl/baucis#145]
Is there any plans to adapt Baucis to work with Koa in the future?
##

**Comment by wprl** [comment]
We will revisit this when node v0.12.0 is released

**Comment by neverfox** [comment]
v0.12.0 has been released. ;)

**Comment by wprl** [comment]
@neverfox  Do you know what kind of "marketshare" koa has currently?

**Comment by neverfox** [comment]
I couldn't say, but we've started using it exclusively at my company. The reception has been glowing online and, unless I'm mistaken, it has the support of the Express team. That said it would be quite a shift for all of the middleware pieces.

On February 23, 2015 11:33:40 AM EST, "William P. Riley-Land - notifications@github.com" <github.soma.3d1062736b.notifications#github.com@ob.0sg.net> wrote:
>@neverfox  Do you know what kind of "marketshare" koa has currently?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wprl/baucis/issues/145#issuecomment-75577694

-- 
Sent from my Android device. Please excuse my brevity.

**Comment by popasquat89** [comment]
It would be great to be able to use Koa with Baucis, I had to write my rest API from scratch again!

**Comment by neverfox** [comment]
[FWIW](https://github.com/LearnBoost/mongoose/issues/2177), Mongoose 4.0 is prepped for easy Koa integration.
