### ISSUE TITLE
Old-style Subcontrollers without schema controller -> subcontroller references

### ISSUE THREAD

**Issue by bojand** [wprl/baucis#173]
In older version of baucis with the older subcontroller framework before introduction of `vivify` it was possible to put controllers into other controllers in very customizable ways. Schema design didn't really dictate how subcontrollers could be set up. For example if we had a `User` model, we could set up REST API for it at `/api/users`. Now let's say we had a `task` model and the schema was such that a user didn't have an array of `tasks` which references the `task` collection but instead each task model had an associated `user` reference. Many tasks would be linked to a single user. We could still create a `tasks` controller such that it is a subcontroller for `user` and would be accessible through `/api/users/:userId/tasks` route. From reading the documentation and looking into the code and tests, it seems that with `vivify` method a `user` schema has to define an array of `tasks` in order for this to be set up? Is this correct or am I misunderstanding something? Is there still a way to setup what I am describing without the `user` having an array of `tasks`? Kinda opposite schema design than what is in the subcontroller test.
##

**Comment by wprl** [comment]
This is implemented in Baucis2, so the issue will be fixed when it is released.
