### ISSUE TITLE
Array updates

### ISSUE THREAD

**Issue by mathurs** [wprl/baucis#207]
When updating mongo documents with arrays mongoose requires markModified field to be set. See the issue in question

http://dfernandez.me/articles/mongoose_array_field_update_problem/

Is it possible to get an API to mark such an update through the GET api.

**Comment by wprl** [comment]
Thanks for the question.  No, this cannot be done out-of-the-box with a GET call, and I would recommend against modifying documents as part of a GET, rather using POST or PUT to update the entity.
