### ISSUE TITLE
Add additional properties to outgoing documents

### ISSUE THREAD

**Issue by hastebrot** [wprl/baucis#211]
Hi! First of all: Baucis is wunderbar!

Is it intentional that I can modify existing properties in `context.doc`, but can't add additional properties? I had to use `context.doc._doc` to copy `_id` to `id`.

~~~js
var through = require("through");

baucis.rest(ExampleModel).request(function(req, res, next) {
  req.baucis.outgoing(through(function(context) {
    context.doc._doc.id = context.doc._doc._id;
    this.queue(context);
  }));
  next();
});
~~~

Also: An hint in the middleware section, that the `document` stage is deprecated in favor of `outgoing` streams, would be nice. :smile:

Regards
Benjamin

**Comment by wprl** [comment]
Actually this isn't a bug.  context.doc is a Mongoose model, and it freezes the properties apparently.  The solution is to add a stream that runs .toJSON() on each context.doc and passes on the new object.  Same as #215

```javascript
req.baucis.outgoing(function (context, next) {
  context.doc = context.doc.toJSON();
  callback(null, context);
});

Cheers
