### ISSUE TITLE
Using dates in query string conditions

### ISSUE THREAD

**Issue by wprl** [wprl/baucis#213]
Need to verify whether or not this is broken.  Example ` http://localhost:3000/api/events?conditions={"date":{"$lte":"2014-09-30T12:00:00.000Z"}}`

**Comment by pjmolina** [comment]
Works for me on baucis version: `1.0.0-candidate.10`
Repro:

Query A: 
`http://localhost:5000/api/citizens?conditions={"birthDate":{"$lte":"1946-07-01T22:01:00.000Z"}}`

* Returns 1 item: 

    `[{"_id":"5486d8d6be89e594103df5b4","birthDate":"1946-07-01T22:00:00.000Z","__v":0}]`

Query B: 
`http://localhost:5000/api/citizens?conditions={"birthDate":{"$lte":"1946-07-01T21:01:00.000Z"}}`

* Returns 0 items.
