### ISSUE TITLE
Error Message Format

### ISSUE THREAD

**Issue by zzswang** [wprl/baucis#220]
Thanks for your great job. 

Here are two suggestions. 

1. We have two different error message formats. It would be better that we follow one unique type.

 {
      "phone": {
          "message": "Path `phone` (13810437618) must be unique.",
          "originalMessage": "E11000 duplicate key error index: juli.users.$phone_1  dup key: { : \"13810437618\" }",
          "name": "MongoError",
          "path": "phone",
          "type": "unique",
          "value": "13810437618"
      }
  }

[
    {
        "message": "Invalid email address.",
        "name": "ValidatorError",
        "path": "email",
        "value": "sdfsdf"
    }
]

2. Provide a middle ware to handle all errors.

**Comment by wprl** [comment]
This is now fixed.  (Mostly.  There will be further improvements in v2.x.)
