### ISSUE TITLE
Nested condition query with $elemMatch and population

### ISSUE THREAD

**Issue by markotom** [wprl/baucis#223]
I need to get documents according to nested condition using `$elemMatch` with populate a path but I don't get it. For example, I need to get all articles of one tag or category with the next schemes:

```js
// Category schema
mongoose.Schema({
  name: String,
  slug: String,
});

// Article schema
mongoose.Schema({
  title: String,
  author: String,
  content: String,
  categories: [{
    type: mongoose.Schema.ObjectId, ref: 'Categories'
  }]
});
```
Then, article controller populate categories:

```js
var controller = baucis.rest('Article');

controller.query('get', function (req, res, next) {
  req.baucis.query.populate('categories');
  next();
});
```

The request `/api/articles?conditions={ "categories": { "$elemMatch": { "slug": "baucis" } } }` seems to work without throwing errors, but I don't get the articles saved on "baucis" category slug.

Am I doing something wrong or is this something to be repaired? Baucis is awesome, btw!

**Comment by wprl** [comment]
Thanks for your question.  Mongoose/Mongo doesn't support using $elemMatch with populate.  You would need to make two calls.  One to get the category IDs that match, then another to get the articles that have those IDs, which can be populated.
