### ISSUE TITLE
Additional empty document is created by baucis controller on a put request

### ISSUE THREAD

**Issue by tomaash** [wprl/baucis#230]
I'm using version 1.0.0-candidate.12 I create baucis controller like this:
```javascript
var Teacher = new mongoose.Schema({
	firstName: String,
	lastName: String,
});
mongoose.model('teacher', Teacher);
baucis.rest('teacher')
```
on put request on previously newly created object, additional empty document gets created. I can workaround it using following middleware:

```javascript
var rejectEmptyObject = function(req, res, next) {
	req.baucis.incoming(function(doc, callback) {
    if (Object.getOwnPropertyNames(doc.incoming).length === 0) {
      res.status(409).send('Cannot save empty object');
      console.log(doc);
      console.log('Empty object filtered out from saving');
      return;
    }
    callback(null, doc);
	});
	next();
};

baucis.rest('teacher').request(rejectEmptyObject);
```
Now with this middleware in action, empty objects are ignored, but it's obviously not the way how to fix this problem.

**Comment by wprl** [comment]
This looks good to me.  Another way to do it would be to add a mongoose validator (or other mongoose middleware) that checks certain fields are not empty.  I'd probably use 422 instead of 409.  You might also consider using `callback(RestError.ValidationError('Cannot save empty object')`
