### ISSUE TITLE
Don't stream the collection when the query count param is used

### ISSUE THREAD

**Issue by wprl** [wprl/baucis#232]

**Comment by pjmolina** [comment]
Hi William! I am addressing the same issue. See here my takes on it.

Currently the `count()` operation is *very slow* as soon the doc count in the mongoDB collection increases.
Some numbers:

*No optimization*
```			
collection	doc count#		time (ms)
A			   8116			 9511 ms
B			  23867			31465 ms
```

My take on this was to hack baucis, detect the `count()` operation and do a direct call to mongoDB bypassing also mongoose.

See the code attached:

`countOptimize.js`
```
function optimizeCount(req, res, next) {
	if (queryIsTotalCount(req)) {
		return directCount(req, res);
	}
	next();
}
function queryIsTotalCount(req) {
	if (req.url === '/?count=true') {
		return true;
	}
	return false;
}
//Direct count bypassing baucis & mongoose
function directCount(req, res) {
	var count = doNativeCount(req.baucis.controller, function(err, count) {

		if (err) {
			res.status(500).json(err);
		}
		else {
			res.status(200).json(count);
		}
	});
}
//Native mongoDB count() bypassing baucis and mongoose 
function doNativeCount(controller, callbackCount) {
	var col = controller.model().collection;
	col.count({}, function(err, count) {
		callbackCount(err, count);
	});
}
	
function apply(controller) {
	controller.request('get', optimizeCount);	
}
module.exports.apply = apply;
```

*Usage*
Pass your baucis controller and apply the middleware patch.
```
require('./countOptimize').apply(your_baucis_controller);
```


Now numbers looks much better:

*Bypass optimization*
```
collection	doc count#		 time(ms)			times faster
A			 8116			  140 ms			   68
B			23867			  139 ms			  226							 
```

Note: this optimize only the full count() with no added query. Other counts are not optimized (see the detection method).

This sample illustrate how to overpass mongoose when needed.

Regards! 
Pedro J.
