### ISSUE TITLE
Request with adding routes

### ISSUE THREAD

**Issue by gilspringer** [wprl/baucis#234]
Hello,

When I call the route /login I have console log "test" but not testOK.
Added route does not use request?

Thank you for your answers.
Best regards

controller.get('/login', function (request, response, next) {
  console.log(test);
  next();
});

controller.request(function (request, response, next) {
console.log(testOK);
  if (request.isAuthenticated()) return next();
  return response.send(401);
});

**Comment by wprl** [comment]
No, if you use .get, .put, etc. it’s just plain Express middleware.

William Riley-Land
Principal & Open Source Consultant
Kun.io App Studio LLC
http://kun.io/wprl
