### ISSUE TITLE
Question on Text queries

### ISSUE THREAD

**Issue by astanciu** [wprl/baucis#235]
Hi

Trying to figure out how to format a Text query. The documentation is a bit confusing, stating this as an example:
GET /api/people?articles={ "summary": { "$text": "dog bites man" } }

In Mongo, my query would look like 
db.users.find({ $text: { $search: "smith" } })

.. having the 'displayname' field Text indexed. I'm not sure how to translate this to Baucis' url format, specifically, in your example, it appears at tho articles is property of the model which has a sub property called 'summary'?? Is that right?

How would I go about doing a text query on a top level property like displayname on an object like:
{
_id: ID,
displayname: "john smith"
}

I tried:
/api/users?conditions={ "summary": { $text: "smith" } }
but it throws the "not valid JSON" error.
Thanks

**Comment by wprl** [comment]
Glad you reported this bug in the documentation.  You also have another issue in your JSON syntax.  The conditions query string parameter exactly matches what will be passed in to `.find` so you need `/api/users?conditions={ "$text": { "$search": "smith" } }`.  Also note that double quotes are required around all object kets in JSON :)

**Comment by astanciu** [comment]
Awesome, that did it! Thanks!!

**Comment by wprl** [comment]
:+1:
