### ISSUE TITLE
Inherit middleware from other controllers

### ISSUE THREAD

**Issue by timbur** [wprl/baucis#242]
Suppose you have some model created via `discriminator` and the parent baucis controller has some middleware that should be applied to said model.  What's the best way to do this?

I'll dig into the baucis source here shortly but I figured it wouldn't hurt to go ahead and start this thread.

You can see my attempt at this through the source of a few relevant modules:

models/User.js
````javascript
'use strict';

// local modules
var ResourceModel = require('../models/Resource.js');
var UserSchema = require('../schemas/User.js');

// define model
var UserModel = ResourceModel.discriminator('User', UserSchema);

/**
 * Expose model.
 */
module.exports = UserModel;
````

controllers/Resource.js
````javascript
'use strict';

// modules
var baucis = require('baucis');

// local modules
var ResourceModel = require('../models/Resource.js');

// initialize controller
var ResourceController = baucis.rest('Resource');

// before creating a resource
ResourceController.request('post', function(req, res, next){
    
    var body = req.body;
    
    // remove these so they default to current time
    delete body.created;
    delete body.modified;
    
    // set to current user
    body.createdBy = getUserId();
    body.modifiedBy = getUserId();
    
    next();

});

// before updating a resource
ResourceController.request('put', function(req, res, next){
    
    var body = req.body;
    
    // remove reserved props
    delete body.created;
    delete body.createdBy;
    
    // set modified props
    body.modified = new Date();
    body.modifiedBy = getUserId();
    
    next();
    
});

/**
 * Gets the user's ID.
 *
 * @api private
 */
function getUserId(){
    return '54fd85b1e062d88803467605';
}

/**
 * Expose controller.
 */
module.exports = ResourceController;
````

controllers/User.js
````javascript
'use strict';

// modules
var util = require('util');
var baucis = require('baucis');
var uniqueValidator = require('mongoose-unique-validator');

// local modules
var ResourceController = require('../controllers/Resource.js');
var UserSchema = require('../schemas/User.js');
var UserModel = require('../models/User.js');

// initialize controller
var UserController = baucis.rest('User');

// inherit resource controller
util.inherits(UserController, ResourceController);

// add plugins
UserSchema.plugin(uniqueValidator);

/**
 * Expose controller.
 */
module.exports = UserController;
````

Unrelated question: Applying the unique validator to the UserSchema isn't going to work here is it?  Do I need to call `plugin` on UserSchema before the UserModel is created?

**Comment by wprl** [comment]
Great question.

Baucis uses [deco](https://www.npmjs.com/package/deco) for decorators instead of prototypal or classical inheritence.  You may find adding deco to your project helps organize your code, but it is not necessary.

For example, you might create a directory called `decorators` in your project.  In it would be a file maybe `set-modified.js`.  The file/directory structure is up to you.  

The decorator:

```javascript
module.exports = function (options) {
  this.request('put', function(req, res, next){

    var body = req.body;

    // remove reserved props
    delete body.created;
    delete body.createdBy;

    // set modified props
    body.modified = new Date();
    body.modifiedBy = getUserId();

    next();

  });
};
```

Then, simply use it like so:

```javascript
var decorator = require('../decorators/set-modified.js');
decorator.apply(ResourceController);
decorator.apply(UserController);
```

To apply a decorator to all controllers baucis creates: 

```javascript
baucis.Controller.decorators(decorator);
```

If you want to take advantage of extra deco features in your project, simply wrap the decorator function in deco:

```javascript
module.exports = deco(function (options) { 
  // ...
});
```

I think yes, you may need to add the schema plugin before it gets added to Mongoose as a model.  

Hope that helps!

**Comment by timbur** [comment]
Perfect!  I really like the decorator pattern.

I implemented most of what you suggested (created `decorators` directory and added `set-modified.js`) plus implemented a really simple way to inherit decorators from other objects while adding decorators.  I like the inheritance route because it's doesn't require me to keep track and update a bunch of other lines any time I want to add some decorator to a base class.  It's plain and explicit inheritance, no OOP.

There might be some method built into `deco` that does this better than what I'm doing, but this works well enough for me:

`decorators/index.js`
````javascript
'use strict';

/**
 * Expose object.
 */
exports = module.exports = {};

/**
 * Adds decorators to some object and/or inherits decorators from others.
 *
 * @param {Object} target
 * @param {Array} decorators
 * @api public
 */
exports.add = function(target, decorators){
    
    if (target._decor === undefined) {
        target._decor = decorators;
    }
    
    decorators.forEach(function(decorator){
        if (decorator._decor === undefined) {
            decorator.apply(target);
        } else {
            exports.add(target, decorator._decor);
        }
    });
    
};
````

`controllers/Resource.js`
````javascript
'use strict';

// modules
var baucis = require('baucis');

// local modules
var decorators = require('../decorators');
var setModified = require('../decorators/set-modified.js');
var ResourceModel = require('../models/Resource.js');

// initialize controller
var ResourceController = baucis.rest('Resource');

// decorate controller
decorators.add(ResourceController, [setModified]);

/**
 * Expose controller.
 */
module.exports = ResourceController;
````

`controllers/User.js`
````javascript
'use strict';

// modules
var baucis = require('baucis');
var uniqueValidator = require('mongoose-unique-validator');

// local modules
var decorators = require('../decorators');
var ResourceController = require('../controllers/Resource.js');
var UserSchema = require('../schemas/User.js');
var UserModel = require('../models/User.js');

// initialize controller
var UserController = baucis.rest('User');

// decorate controller
decorators.add(UserController, [ResourceController]);

// force unique names
UserSchema.path('name', {
    type: String,
    required: true,
    unique: true
});
UserSchema.plugin(uniqueValidator);

/**
 * Expose controller.
 */
module.exports = UserController;
````

Also, regarding the plugins for anyone wondering, it works to add the plugin to the schema after the schema was used to create the model.  I just needed to use the `Schema.path` method to set the `name` property's `unique` field to `true`.

One last thing!  Baucis is **awesome**!!!  I spent the past couple of weeks trying to determine the absolute best library to use for the backend of the service I'm building, and Baucis is by far the best.  I tried LoopBack, SailsJS, node-restful, and read up on a few others, and nothing beats the simplicity of Baucis while simultaneously being infinitely flexible.  I also really like knowing that there's no magical funny business going on behind the scenes that might bite me in the butt later on.  What you see is exactly what you get with Baucis.
