### ISSUE TITLE
Different namespaces (environments) for resources?

### ISSUE THREAD

**Issue by timbur** [wprl/baucis#243]
Sorry to somewhat abuse the issues section to ask questions, but my question is regarding how to achieve the following with Baucis:

Suppose I have a development API and a production API, where resources can be accessed in the development environment via something like `/dev/resources/:id` and in the production environment via something like `/resources/:id`.  What's the best way to achieve this without creating a bunch of duplicate code?

**Comment by wprl** [comment]
Not an abuse at all.  Feel free to ask questions.  

I'd do something more or less like:

```javascript

var app = express();

// ...add controllers to baucis, etc...

var api = baucis();

if (process.env.NODE_ENV === 'production') {
  app.use(api);
}
else {
  app.use('/dev', api);
}
```

**Comment by timbur** [comment]
I should have made my question more clear, sorry.  The server serves both development and production resources at the same time.  For example, users might update some resource at `domain.com/dev/resources/:id` and then at some point they'll POST to `domain.com/dev/resources/:id/deploy`, which will then move their changes to the production endpoint `domain.com/resources/:id`.

**Comment by wprl** [comment]
I think you'd want to do something like this.  You'd have a flag in the Mongo documents maybe `isDeployed`.  You'd create two APIs for the different "realms."  Each "realm" would have some middleware to alter `request.baucis.query` to restrict the query to, for dev `isDeployed: false` or for prod `isDeployed: true`.  You'd `app.use('/dev', baucis())`, then set up the prod API and do `app.use(baucis())`.  For the dev resources controller you'd add `controller.post('/:id/deploy', function () {...})` with your custom code (this is just a vanilla Express route.)  

Something along these lines, does that make sense?

**Comment by timbur** [comment]
Thanks for the quick response.  That's roughly what I was expecting, but I'm not sure I fully understand or maybe I need to elaborate some more.  I would like for the production endpoints to be unaffected by changes made in the development environment (until deploy of course).  Does that implementation allow for this?  I can't see how it would or maybe I'm misunderstanding something.  If not, I was thinking maybe it would make sense to add some sort of middleware that either automatically prefixes the property keys with `dev:` or somehow automatically have separate collections, one for production and one for development.

**Comment by timbur** [comment]
It looks like mongoose already comes with prefix functionality but I'm not sure what the point of it is since I only see it within `Schema.add`: http://mongoosejs.com/docs/api.html#schema_Schema-add

Right now I'm putting together a decorator that should provide the desired functionality.

**Comment by wprl** [comment]
Np.  I think I understand what you're asking now…

I would approach it like this.  There are a lot of ways to do this that may be better or worse for your specific problem.  The following avoids any joins or need for additional collections. 

I'd use `_id` as the field to store version since it can be thought of as a timestamp.  I'd use let's say `identifier` that identifies a thread of updates across multiple revisions (this could be a string or ObjectId or number).  And also a field `deployed`, a boolean.

You'd set the findBy for both controllers to `identifier`.  The dev controller would filter the Mongoose query to always return the document with matching `identifier` with highest `_id` field.  The prod controller would filter to the matching `identifier`, highest `_id`, and additionally on `deployed: true` so that the most recent matching document that has been deployed will be selected.

**Comment by timbur** [comment]
Makes sense.  This would make `identifier` the new `id` and keep a full history of all versions of some resource, right?  I like this idea but then again I'm not sure I like how much disk space it would require.  To remedy that, I could implement some diffing middleware (my original backend already logs all diffs anyway, so it would be trivial), which has prompted me to look into a git implementation for Node+MongoDB (which would actually be ideal for my use case) but I haven't found much yet.  I did however find [Vermongo](https://github.com/thiloplanz/v7files/wiki/Vermongo), which uses "shadow" collections, so I might be able to see how Vermongo does that and implement something similar but for only two different versions to minimize disk space requirements.

**Comment by wprl** [comment]
Makes sense.  If you're sure you will only have a published version and unpublished version, you might just have a document with two root-level fields, prod, and dev that both store the same fields.  Good luck!

**Comment by timbur** [comment]
Off the top of your head @wprl, which "gotchas" should I look out for with the following implementation?  E.g., when using `populate` or something.

I ended up going the decorator route since it fits my particular use-case the best.  One of the main requirements is that certain properties should be the same in both environments no matter what, and I think a decorator gives me more control over how to do this, plus it keeps disk usage to a minimum.

The decorator is pretty simple.  It adds support for a special `env` field to the schema and modifies or copies the request body and response accordingly, prefixing `dev:` to property keys.


`decorators/env.js` (Not complete but works well enough so far.)
````javascript
'use strict';

// local modules
var getSchema = require('./index.js').getSchema;
var getPaths = require('./index.js').getPaths;

// constants
var PREFIX = 'dev:';

/**
 * Expose function.
 */
module.exports = env;

/**
 * Automatically prefixes property keys with `dev:` when accessing the api via
 * `/dev/api`.
 *
 * @api public
 */
function env () {
    
    var schema = getSchema(this);
    var paths = getPaths(this);
    var keys = [];
    var copies = {};
    
    // gather affected keys and copies
    Object.keys(paths).forEach(function (key) {
        
        var options = paths[key].options;
        
        if (
            // some paths may have no environment
            options.env !== false
            && options.select !== false
            // also ignore `_id`, `__v`, etc.
            && key.substring(0, 1) !== '_'
        ) {
            keys.push(key);
            copies[key] = options;
        }
        
    });
    
    // add copies
    schema.add(copies, PREFIX);
    
    // when getting a resource
    this.request('get', function (req, res, next) {
        
        var select = req.query.select || '';
        var split = select.split(' ');
        
        if (inDevelopment(req)) {
            
            // hide normal keys
            keys.forEach(function(key){
                split.push('-'+key);
            });
            
            req.baucis.outgoing(function (context, callback) {
                var doc = context.doc.toJSON();
                context.doc = doc;
                // replace response's prefixed keys with their normal versions
                keys.forEach(function (key) {
                    var prefixedKey = PREFIX+key;
                    if (doc[prefixedKey] !== undefined) {
                        doc[key] = doc[prefixedKey];
                        delete doc[prefixedKey];
                    }
                });
                callback(null, context);
            });
            
        } else {
            
            // hide development keys
            keys.forEach(function(key){
                split.push('-dev:'+key);
            });
            
        }
        
        req.query.select = split.join(' ');
        
        next();

    });
    
    // when creating a resource
    this.request('post', function (req, res, next) {
        
        var body = req.body;
        
        // copy all keys to their prefixed versions
        keys.forEach(function (key) {
            var prefixedKey = PREFIX+key;
            body[prefixedKey] = body[key];
        });
        
        next();

    });
    
    // when updating a resource
    this.request('put', function (req, res, next) {
        
        if (inDevelopment(req)) {
            
            // replace keys with their prefixed versions
            keys.forEach(function (key) {
                var prefixedKey = PREFIX+key;
                body[prefixedKey] = body[key];
                delete body[key];
            });
            
        }
        
        next();

    });

}

/**
 * Determines whether or not the request was made in the dev environment.
 *
 * @param {Object} req Express request
 * @return {Boolean} true if in development
 * @api private
 */
function inDevelopment (req) {
    
    return req.baseUrl.indexOf('/dev/api/') === 0;
    
}
````

Example schema snippet:
````javascript
{
        created: {
            type: Date,
            default: Date.now,
            required: true,
            reserved: true,
            env: false
        },
        
        createdBy: {
            type: ObjectId,
            ref: 'User',
            default: userUtils.getId,
            required: true,
            reserved: true,
            env: false
        },
        
        modified: {
            type: Date,
            required: true,
            reserved: true,
            update: Date.now,
            env: false
        },
        
        modifiedBy: {
            type: ObjectId,
            ref: 'User',
            required: true,
            reserved: true,
            update: userUtils.getId,
            env: false
        },
        
        // descriptive
        
        name: {
            type: String,
            trim: true,
            required: true
        }
}
````


And the decorator of course only took a second to add.

`controllers/Resource.js`
````javascript
'use strict';

// modules
var baucis = require('baucis');

// local modules
var decorators = require('../decorators');
var reserved = require('../decorators/reserved.js');
var once = require('../decorators/once.js');
var update = require('../decorators/update.js');
var env = require('../decorators/env.js');
var ResourceModel = require('../models/Resource.js');

// initialize controller
var ResourceController = baucis.rest('Resource');

// decorate controller
decorators.add(ResourceController, [
    reserved,
    once,
    update,
    env
]);

/**
 * Expose controller.
 */
module.exports = ResourceController;
````

**Comment by timbur** [comment]
Hmm... Just saw your last post and that seems way easier.  But I'm not sure how I would make it work properly with queries, populating, etc.

**Comment by wprl** [comment]
Glad it helped!
