### ISSUE TITLE
Error by implementing to angular-fullstack-generator

### ISSUE THREAD

**Issue by Macomb87** [wprl/baucis#245]
Hello! I got some wierd error by implementing baucis to angular-fullstack-generator. 
1. I'm setting up new project with  "yo angular-fullstack  [name]" 
2. and  i dont change versions of  it just express to 4.12.0 and update node modules.
3. Then i'm installing baucis with npm install --save baucis and it install it normaly 
4. i'm implementing baucis to app.js in project as told in instructions  var baucis = require('baucis') works fine .. but when i add app.use('/api',baucis()); after var app = express(); app throws me an error : 

![errror](https://cloud.githubusercontent.com/assets/4944513/6730888/a78852a6-ce40-11e4-8fef-8caa7cd8b758.png)

what to do ?

**Comment by wprl** [comment]
I am able to reproduce that error if I add the baucis API middleware to the app before adding any models to baucis.  I got it to work as below. (I think, I've not used this generator before.)

```javascript
/**
 * Main application file
 */

'use strict';

// Set default node environment to development
process.env.NODE_ENV = process.env.NODE_ENV || 'development';

var express = require('express');
var mongoose = require('mongoose');
var config = require('./config/environment');
var baucis = require('baucis');

// Connect to database
mongoose.connect(config.mongo.uri, config.mongo.options);

// Populate DB with sample data
if(config.seedDB) { require('./config/seed'); }


// Setup server
var app = express();
var server = require('http').createServer(app);
var socketio = require('socket.io')(server, {
  serveClient: (config.env === 'production') ? false : true,
  path: '/socket.io-client'
});
require('./config/socketio')(socketio);
require('./config/express')(app);
require('./routes')(app);

baucis.rest('User');
app.use('/api', baucis());


// Start server
server.listen(config.port, config.ip, function () {
  console.log('Express server listening on %d, in %s mode', config.port, app.get('env'));
});

// Expose app
exports = module.exports = app;
```

So I think 1) you may be doing something out of order, and 2) the baucis documentation needs to be updated and a better error message should be generated by baucis in this situation

Let us know if you run into any other issues!

**Comment by Macomb87** [comment]
actualy i did this ... 


'use strict';

// Set default node environment to development
process.env.NODE_ENV = process.env.NODE_ENV || 'development';

var express = require('express');
var mongoose = require('mongoose');
var config = require('./config/environment');
var baucis = require('baucis');
// Connect to database
mongoose.connect(config.mongo.uri, config.mongo.options);

// Populate DB with sample data
if(config.seedDB) { require('./config/seed'); }

// Setup server
var app = express();
app.use('/rest',baucis());
var server = require('http').createServer(app);
require('./config/express')(app);
require('./routes')(app);

// Start server
server.listen(config.port, config.ip, function () {
  console.log('Express server listening on %d, in %s mode', config.port, app.get('env'));
});

// Expose app
exports = module.exports = app;



so i'm wondering what is your package.json ? what version of modules  ?


{
  "name": "test",
  "version": "0.0.0",
  "main": "server/app.js",
  "dependencies": {
    "baucis": "^1.0.5",
    "body-parser": "~1.5.0",
    "bson": "^0.2.20",
    "composable-middleware": "^0.3.0",
    "compression": "~1.0.1",
    "connect-mongo": "^0.4.1",
    "cookie-parser": "~1.0.1",
    "ejs": "~0.8.4",
    "errorhandler": "~1.0.0",
    "express": "~4.12.0",
    "express-jwt": "^0.1.3",
    "express-session": "~1.0.2",
    "jsonwebtoken": "^0.3.0",
    "lodash": "~2.4.1",
    "method-override": "~1.0.0",
    "mongoose": "~3.8.8",
    "morgan": "~1.0.0",
    "passport": "~0.2.0",
    "passport-facebook": "latest",
    "passport-google-oauth": "latest",
    "passport-local": "~0.1.6",
    "passport-twitter": "latest",
    "serve-favicon": "~2.0.1"
  },
  "devDependencies": {
    "grunt": "~0.4.4",
    "grunt-autoprefixer": "~0.7.2",
    "grunt-wiredep": "~1.8.0",
    "grunt-concurrent": "~0.5.0",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-concat": "~0.4.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-htmlmin": "~0.2.0",
    "grunt-contrib-imagemin": "~0.7.1",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-google-cdn": "~0.4.0",
    "grunt-newer": "~0.7.0",
    "grunt-ng-annotate": "^0.2.3",
    "grunt-rev": "~0.1.0",
    "grunt-svgmin": "~0.4.0",
    "grunt-usemin": "~2.1.1",
    "grunt-env": "~0.4.1",
    "grunt-node-inspector": "~0.1.5",
    "grunt-nodemon": "~0.2.0",
    "grunt-angular-templates": "^0.5.4",
    "grunt-dom-munger": "^3.4.0",
    "grunt-protractor-runner": "^1.1.0",
    "grunt-asset-injector": "^0.1.0",
    "grunt-karma": "~0.8.2",
    "grunt-build-control": "DaftMonk/grunt-build-control",
    "grunt-mocha-test": "~0.10.2",
    "grunt-contrib-sass": "^0.7.3",
    "jit-grunt": "^0.5.0",
    "time-grunt": "~0.3.1",
    "grunt-express-server": "~0.4.17",
    "grunt-open": "~0.2.3",
    "open": "~0.0.4",
    "jshint-stylish": "~0.1.5",
    "connect-livereload": "~0.4.0",
    "karma-ng-scenario": "~0.1.0",
    "karma-firefox-launcher": "~0.1.3",
    "karma-script-launcher": "~0.1.0",
    "karma-html2js-preprocessor": "~0.1.0",
    "karma-ng-jade2js-preprocessor": "^0.1.2",
    "karma-jasmine": "~0.1.5",
    "karma-chrome-launcher": "~0.1.3",
    "requirejs": "~2.1.11",
    "karma-requirejs": "~0.2.1",
    "karma-coffee-preprocessor": "~0.2.1",
    "karma-jade-preprocessor": "0.0.11",
    "karma-phantomjs-launcher": "~0.1.4",
    "karma": "~0.12.9",
    "karma-ng-html2js-preprocessor": "~0.1.0",
    "supertest": "~0.11.0",
    "should": "~3.3.1"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "start": "node server/app.js",
    "test": "grunt test",
    "update-webdriver": "node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update"
  },
  "private": true
}

**Comment by wprl** [comment]
The problem is you need to add models to baucis e.g. call `baucis.rest('User')`, and you need to do it before you call `baucis()`.

**Comment by Macomb87** [comment]
ok i dont get it now .. but .. i configured that all on /rest url path ...
is using baucis....  so when i call http://localhost:9000/rest/users/:id
<-- i get one user or ...http://localhost:9000/rest/users <-- all users
thsi is how is write in document how to implement baucis  or did that
changed with version 1.0.5 ?

Lp,
Marko Obradovič

2015-03-20 0:29 GMT+01:00 William P. Riley-Land <notifications@github.com>:

**Comment by wprl** [comment]
As long as you do `app.use('/rest', baucis())` it should be working at those URLs.

**Comment by Macomb87** [comment]
Yes ... i know i had before like that but it doesnt work anymore i dont
know how to implement now. but i had models in seperate files .... and
there i implement like that


APP.js

/**
 * Main application file
 */

'use strict';

// Set default node environment to development
process.env.NODE_ENV = process.env.NODE_ENV || 'development';

var express = require('express');
var mongoose = require('mongoose');
var config = require('./config/environment');
var baucis = require('baucis');

// Connect to database
mongoose.connect(config.mongo.uri, config.mongo.options);

// Populate DB with sample data
if(config.seedDB) { require('./config/seed'); }

// Setup server
var app = express();
app.use('/rest', baucis());
var server = require('http').createServer(app);
require('./config/express')(app);
require('./routes')(app);

// Start server
server.listen(config.port, config.ip, function () {
  console.log('Express server listening on %d, in %s mode',
config.port, app.get('env'));
});

// Expose app

exports = module.exports = app;



this is app.js


EVENT.mode.js

module.exports = mongoose.model('Event', EventSchema);
var baucis = require('baucis');
var c = baucis.rest('Event');

AND like that worked fine but now it doesnt any more i dont know what
changed  i was using "baucis": "^1.0.0-candidate.12",

**Comment by wprl** [comment]
As long as you `require` event.mode.js before calling `app.use('/rest', baucis())` it should be working.  Are you getting a new error message now?

**Comment by Macomb87** [comment]
in this case what i pasted you the code it is a working sample .... but
when i created new projects with angular-fullstack-generator it doesnt work
anymore..... I do the same procedure as allways and doesn't work.

Lp,
Marko Obradovič

2015-03-20 1:53 GMT+01:00 William P. Riley-Land <notifications@github.com>:

**Comment by wprl** [comment]
I'm still not seeing where you are adding models before calling `baucis()`.  Some things have changes from 1.0.0-prerelease.x to 1.0.x so you may need to stick with the older version until you have time to update your code to work wit 1.0.x.
