### ISSUE TITLE
Does baucis work fine with mongoose@4.0.0 ?

### ISSUE THREAD

**Issue by idy** [wprl/baucis#248]

**Comment by wprl** [comment]
It looks like it is, at least for the most part.  Most of the tests run with 4.x and the ones that fail look minor (like error message wording changes).  I'd say go for it.

**Comment by timbur** [comment]
I have a noob question: What's the best way to do this?  Fork baucis and update its package.json?  I'm having issues with peerDependencies otherwise.

**Comment by wprl** [comment]
Oficially supported in v1.3.0
