### ISSUE TITLE
How to search in a subcollection ?

### ISSUE THREAD

**Issue by playUruguay** [wprl/baucis#249]
I need to filter this query by users that contains roles with idAction=550077dd4ffd77bc1f90d8a9

request.baucis.query.where('roles[].idAction',550077dd4ffd77bc1f90d8a9);

the moongose model is
var UserSchema = new mongoose.Schema({
	name: {
        type: String,
        required: true
    },
    roles: [{
        idAction: { 
            type: mongoose.Schema.Types.ObjectId, 
        },
        action: { 
            type: String
        }  
    }]
});

**Comment by wprl** [comment]
Looks like you figured it out.  Let us know if you have any other questions!
