### ISSUE TITLE
Best way to simulate a request internally?

### ISSUE THREAD

**Issue by timbur** [wprl/baucis#250]
This might belong in the express repo but I figured it wouldn't hurt to ask here.  Suppose I have a `clone` method on some controller:

```js
controller.post(':id/clone', function (req, res, next) {
  // simulate the GET request to retrieve the resource as the user normally would see it
  // maybe change a couple of values
  // simulate the POST request to create the clone and return the response as usual
});
```

This internal simulation is necessary because I have a handful of decorators attached to requests that filter and validate certain properties based on user permissions, etc., and it would be a pain to refactor them into this `clone` decorator, especially if I can simulate the requests.

I've done something like this before, but it was pretty hacked together, as I had to dig into the internals of Express and "fake" the request and response handler. Surely there's a better way?

**Comment by wprl** [comment]
Hi Tim,

My first thought would probably be to use the request module and just reconnect back to localhost (or wherever) for the two new requests… not sure that’s the best solution, but keeps the code clean anyway!  It might be nice to have a way to ask baucis to do this without involving middleware/requests… I’ll think on that.

Cheers,
William

William Riley-Land
Principal & Open Source Consultant
Kun.io App Studio LLC
http://kun.io/wprl
