### ISSUE TITLE
OR operation in baucis query

### ISSUE THREAD

**Issue by playUruguay** [wprl/baucis#251]
request.baucis.query.where('idUser OR idUserTo.id', request.user._id.toString() );

**Comment by pjmolina** [comment]
The `where` method is the mongosee/mongoDB query API. Therefore `OR` operator is already built-in.

To use it, you need to employ the following JSON-like syntax:
```
request.baucis.query.where({'$or':[
   {
      idUser : request.user._id.toString()
   },
   {
      idUserTo : request.user._id.toString()
   }
]});
```

Same case aplies for AND. Full doc: [http://docs.mongodb.org/manual/reference/operator/query/or/](http://docs.mongodb.org/manual/reference/operator/query/or/)

**Comment by playUruguay** [comment]
Hi pjmolina, 
Thanks for the answer, but the problem is idUserTo is a child collection of id's. How do I solve it ?
Thanks in advance

**Comment by pjmolina** [comment]
Ok. Then probably the `$matchElement` will do the trick for you: [http://docs.mongodb.org/manual/reference/operator/query/elemMatch/#op._S_elemMatch](http://docs.mongodb.org/manual/reference/operator/query/elemMatch/#op._S_elemMatch)

**Comment by pjmolina** [comment]
Fix typo: `$elemMatch`

**Comment by playUruguay** [comment]
Thanks for help me! 

Here the solution: 

request.baucis.query.where({'$or':[
	   {
	      idUser : request.user._id.toString()
	   },
	   {
	      idUserTo:
	       {
	          $elemMatch:
	            {
	               id: request.user._id.toString() 
	            }
	       }
	   }
	]});

**Comment by wprl** [comment]
Thanks @pjmolina !
