### ISSUE TITLE
Applying decorators to populated fields?

### ISSUE THREAD

**Issue by timbur** [wprl/baucis#252]
What's the best way to approach this?  I can elaborate and provide a detailed example if necessary.

**Comment by wprl** [comment]
What kind of decorators are you using?  Deco?

**Comment by timbur** [comment]
Not `deco` exactly but it works similarly.  I made something for my use-case a while back for inheriting decorators from other controllers.

Boils down to this (like you recommended a while back):
```js
decorator.apply(this);
```

**Comment by wprl** [comment]
Maybe I need to see a full example but would `decorator.apply(this.something)` not work?

**Comment by timbur** [comment]
Does `baucis` rely on certain `deco` methods to apply decorators to the populated fields?  Or is there a pattern I can use to make it happen?  E.g., something like the monkey-patching at the end of  `baucis/Model.js`?

**Comment by timbur** [comment]
Quick example:

I have a `vote` decorator that, instead of returning the list of people who have voted, it will return the number, so a typical response to some request for some resource might look like:
```json
{
  "_id": "comment1",
  "comment": "example",
  "voted": 20
}
```

And you might, for example, be able to populate the replies to the comment, which might look like this:
```json
{
  "_id": "comment1",
  "comment": "example",
  "voted": 20,
  "replies": [
    {
      "_id": "comment2",
      "comment": "some reply",
      "voted": [
        "user1",
        "user2",
        "user3"
      ]
    }
  ]
}
```

But I need the `vote` decorator to be applied to the populated list `replies` so that, for example, `voted` returns `3` instead of the list:
```json
{
  "_id": "comment1",
  "comment": "example",
  "voted": 20,
  "replies": [
    {
      "_id": "comment2",
      "comment": "some reply",
      "voted": 3
    }
  ]
}
```

**Comment by timbur** [comment]
Perhaps I need to transfer the decorator logic from the baucis controllers to the mongoose schema/models themselves?  Although I'm not sure how feasible this would be for certain functionality.

**Comment by timbur** [comment]
Alright so... I first tried moving everything into mongoose plugins instead of decorating the baucis controllers, but it ended up being too hacky to pass the Express request object into the mongoose plugins, so I then moved everything back into the baucis controllers.  It would seem the best solution is to keep track of which fields are being populated/selected and then go deep into the outgoing docs to apply the custom decorator(s) logic.  I'll create a repo with all my code at some point if anyone is interested.

**Comment by wprl** [comment]
It would be great to see your code in a wiki page, or linked from the wiki!

**Comment by timbur** [comment]
@wprl I'm planning on creating a bunch of repos for all the different decorators plus a few other modules... as soon as I complete a handful of other things.  :)

**Comment by wprl** [comment]
@timbur no rush!  I know the feeling.

**Comment by timbur** [comment]
Went ahead and open sourced all the decorators I've put together.  They all needs test and a handful are still a WIP but everything works for my use-cases.  See [`baucis-decorators`](https://github.com/loggur/baucis-decorators).

**Comment by wprl** [comment]
Tim these look awesome!  Looking forward to digging in to them more  towards the end of the month. Let me know if I can help promote your work.

**Comment by timbur** [comment]
I'm eager to hear your feedback.  :)  I have a feeling you would have preferred that I used `deco`, but I basically just took it a step at a time, doing what made sense to me along the way.

One of the more interesting decorators is the [deep select](https://github.com/loggur/baucis-decorator-deep-select), I think.  Namely the code surrounding these two comments: [unshift each doc to process the deepest ones first](https://github.com/loggur/baucis-decorator-deep-select/blob/master/index.js#L87-L88) and [unshift again within `outgoing` to put them back in the proper order](https://github.com/loggur/baucis-decorator-deep-select/blob/master/index.js#L57-L58).
