### ISSUE TITLE
Migration Problem: Multiple Baucis-Middleware instances

### ISSUE THREAD

**Issue by PhilJ** [wprl/baucis#253]
I currently migrating an app from baucis 0.18 to the recent release - but I'm failing to migrate the existent architecture. 

Maybe you have an idea how to fix this without totally refactoring my code: My current architecture creates multiple baucis middlewares and summarizes them into one express app. It seems to me that the current version of baucis only allows to call baucis() once per app and my current architecture wont work any longer (endpoints are not longer reachable and I receive the error on console `Internal Server Error: Baucis request property already created (500).`) - is that correct? 

Currently I have a number (about 15) of mongoose models. For each model exists an API file with setups and extends an baucis rest controller and returns a baucis rest middleware (sometimes wrapped in an express app) 

    // baucisApi1.js
    module.exports = function (config) {
        var controller = baucis.rest('ModelName').select(...);
        // extending controller ...
        var api = baucis();
        // adding custom routes to api
        return api;
    }

This files all get summarized to an express app `api.js`

    // api.js
    var app = express();
    app.use(require('./baucisApi1')(config));
    app.use(require('./baucisApi2')(config));
    ...

**Is there any way how I could still create multiple middleware instances from baucis or how I could define baucis model controllers in multiple files?** I tried to remove the `baucis()` calls from baucisApiX.js files and calling it only once in api.js but I couldn't reach the rest endpoints)

Thanks in advance for your support!

**Comment by timbur** [comment]
You can attach routes to the `baucis` controller as it is essentially an `express.Router`.

So your `baucisApi1.js` might look like (returns controller instead of api):
```js
module.exports = function (config) {
    var controller = baucis.rest('ModelName').select(...);
    // extending controller ...
    // adding custom routes to controller
    controller.use(function (req, res, next) {
        // etc.
    });
    controller.request('get post put', function (req, res, next) {
        // etc.
        // e.g., filter outgoing
    });
    controller.post('/login', function (req, res, next) {
        // the endpoint would look something like /api/ModelNames/login
    });
    return controller;
}
```

The way I've organized my app is as follows.  Apologies for the huge wall of code but perhaps it will help you see what you might need to change to make your models work more flexibly with `baucis`.

`server/app.js`
```js
'use strict';

// initialize express
var express = require('express');
var app = express();
var server = app.listen(process.env.PORT || 8080);

/**
 * Expose app.
 */
module.exports = app;

// log errors
app.on('error', function (err) {
  console.log('App Error:', err);
});

// set app environment
var env = process.env.NODE_ENV || 'development';
app.set('env', env);

// initialize database
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/db');

// initialize baucis and swagger
var baucis = require('baucis');
var swagger = require('baucis-swagger');

// enable sessions, parsers, etc. here
/* ... */

// serve REST api
var api = require('../routes/api.js');
app.use('/api', api);

// serve static assets
app.use(express.static(__dirname+'/client'));
```

`routes/api.js`
```js
'use strict';

// modules
var baucis = require('baucis');
var swagger = require('baucis-swagger');

// controllers
var ResourceController  = require('../controllers/Resource.js');
var UserController      = require('../controllers/User.js');
var LogController       = require('../controllers/Log.js');
var PageController      = require('../controllers/Page.js');
var ModuleController    = require('../controllers/Module.js');
var InstanceController  = require('../controllers/Instance.js');

/**
 * Expose router.
 */
module.exports = baucis();
```

And then my controllers look something like this:
`controllers/User.js`
```js
'use strict';

// modules
var baucis = require('baucis');
var mongoose = require('mongoose');
var ObjectId = mongoose.Types.ObjectId;

// local modules
var decorators         = require('../decorators');
var guests             = require('../decorators/guests.js');
var upgrade            = require('../decorators/upgrade.js');
var ResourceController = require('../controllers/Resource.js');

// ensure model is initialized
var UserModel = require('../models/User.js');

// initialize controller
var UserController = baucis.rest('User');

// decorate controller
decorators.add(UserController, [
  guests,
  upgrade,
  ResourceController
]);

/**
 * Expose controller.
 */
module.exports = UserController;
```

`models/User.js`
```js
'use strict';

// modules
var mongoose = require('mongoose');

// local modules
var UserSchema = require('../schemas/User.js');

// define model
var UserModel = mongoose.model('User', UserSchema);

/**
 * Expose model.
 */
module.exports = UserModel;
```

At some point I'll probably factor most of this into something a bit more reusable but it works well enough for me.

**Comment by wprl** [comment]
@PhilJ did that answer your question?
