### ISSUE TITLE
Remove field with PUT

### ISSUE THREAD

**Issue by Tchouk** [wprl/baucis#255]
Is it possible to update a resource with PUT to remove a useless field ? Until now I use PUT to make the useless field null.

**Comment by wprl** [comment]
No, there's not a good way to do this currently.  That would be a good feature.

**Comment by wprl** [comment]
Actually, this should be possible by PUT'ing a body that uses the `$unset` update operator http://docs.mongodb.org/manual/reference/operator/update/unset/
