### ISSUE TITLE
Question: Is it possible to add custom routes without a mongoose model?

### ISSUE THREAD

**Issue by jomaora** [wprl/baucis#259]
Hello,

I have made a controller with some routes to allow launch some operations on my application. It can be called on /task. I allow to make POSTS on this routes.

I would like to see them on my swagger ui, but there's no task schema on my database (and I don't want to create one, and this routes are not defined on some controller with model because the logic in this routes doesn't belog to the models that will be impacted). 

```
{
    path: '/block/:element/user/:userId',
    description: 'block an element for a user',
    operations: [
        {
            httpMethod: 'POST',
            summary: 'block an element for a user',
            parameters: [
                {
                        paramType: 'path',
                        name: 'element',
                        dataType: 'string',
                        required: true
                },
                {
                        paramType: 'path',
                        name: 'userId',
                        description: 'ID of the user',
                        dataType: 'string',
                        required: true
                }
            ],
            errorResponses: [
                {
                    code: 403,
                    reason: 'User not allowed.'
                },
                {
                    code: 404,
                    reason: 'User not found.'
                }
            ]
        }
    ]
}

**Comment by wprl** [comment]
Great question.  You can just add it directly to the definition.  Check out this page in the Wiki: https://github.com/wprl/baucis/wiki/Swagger Also checkout the swagger2 plugin.  I believe their README describes how to alter the definitions if using that plugin.
