### ISSUE TITLE
Change default output?

### ISSUE THREAD

**Issue by leandono** [wprl/baucis#261]
First, congrats for this great module!
I'm just a little stuck trying to change systematically the default output of every response of the API... for example, I want to wrap the response in another object, something like this:

```
{
status: 'success',
data: [docs outputted by baucis]
}
```

I saw that I can change every document using `request.baucis.outgoing`, but I can't find how change all the output of the response.

Cheers!

**Comment by wprl** [comment]
Currently, the best option is to create a stream that outputs one document based on n incoming documents.  The easiest way to do this would be synchronously, and unless you accept or respond large collections of objects this shouldn't be much of a performance hit.  

I'm working on some similar functionality for the HAL/JSON-API/JSONP plugins so I'll have a more concrete example at some point.

I'll leave this open as a reminder to add a code example to the wiki.

**Comment by jamesvillarrubia** [comment]
I'd actually like to see this example.  I'm trying to normalize (normalizr) the results from baucis but I can't seem to get anything besides documents specific stuff.   Now I'm hacking something into the outgoing function, but also trying to figure out how to do it synchronously.  Any help or direction would be appreciated!

**Comment by wprl** [comment]
Unfortunately, there's not a user friendly way to do it.  I think the easiest way would be to fork baucis-json-strict to wrap the response text in the additional JSON, and/or to add a duplex stream with `request.baucis.outgoing` that aggregates a stream of objects into an output stream of a single object.  

https://github.com/wprl/baucis/wiki/Streaming
https://github.com/wprl/baucis-json

This will possibly ship in v2.0.0, or possibly later.  (Depending on whether HTTP/2 headers or HAL+JSON are used to add hypermedia meta data to responses.)
