### ISSUE TITLE
npm baucis 1.3.1 is broken

### ISSUE THREAD

**Issue by pjmolina** [wprl/baucis#265]
NPM package for Baucis 1.3.1 is broken due to a missing dependence on: `baucis-links` not found in the npm registry.

**Repro command** 
`npm install baucis` 

Output:
```
npm ERR! 404 404 Not Found: baucis-links
npm ERR! 404
npm ERR! 404 'baucis-links' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'baucis'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

**Comment by pjmolina** [comment]
I see you already has the code here: [https://github.com/wprl/baucis-links](https://github.com/wprl/baucis-links). Maybe it just a question of making a `npm publish ./` on your side, isn't it? ;-)

**Comment by ztripez** [comment]
I have the same problem

**Comment by pjmolina** [comment]
@ztripez A temporal work-around is to add the dependence by hand in the `package.json` pointing to github sources:

```
...
  "dependencies": {
	"baucis": "1.3.1",
	"baucis-links": "git://github.com/wprl/baucis-links#master"
  },
...
```

An then to do a `npm install`

**Comment by ztripez** [comment]
thanks

**Comment by wprl** [comment]
Thanks guys, it should be fixed now.  I published it to a private npm registry by mistake.

**Comment by pjmolina** [comment]
Nice! Thanks!
