### ISSUE TITLE
Sync on policy about mongoose required version on peerDependecies

### ISSUE THREAD

**Issue by pjmolina** [wprl/baucis#266]
Hi!
Doing a project using `baucis`, `baucis-swagger` and `baucis-swagger2` I was forcing it to use `mongoose 4.0.2`

Then, I found the following npm error:
 
```
$ npm install
npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer baucis@1.3.1 wants mongoose@>=3 <5
npm ERR! peerinvalid Peer baucis-swagger@1.1.1 wants mongoose@^3.8.23
npm ERR! peerinvalid Peer baucis-swagger2@0.1.5 wants mongoose@^4.0.2
```
Different packages requires different constraints about what mongoose version to use.

I feel comfortable if everyone uses the same policy as baucis here across plugins = `>=3 <5`
to allow 3.x and 4.x without restrictions?

What do you think guys?

**Comment by wprl** [comment]
Makes sense

**Comment by wprl** [comment]
All the plugins are updated!

**Comment by pjmolina** [comment]
Great. I am doing the same on baucis-swagger2.

**Comment by pjmolina** [comment]
Hi. This issue has appeared again. The commit https://github.com/wprl/baucis/commit/e81125fc494f9dd74029748851e25fc4f02c96d6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 has broken it.

See this:
```
> npm install
npm ERR! peerinvalid The package mongoose does not satisfy its siblings' p
npm ERR! peerinvalid Peer baucis@1.5.0 wants mongoose@3 - 4.0.4
npm ERR! peerinvalid Peer baucis-swagger@1.1.2 wants mongoose@>=3 <5
npm ERR! peerinvalid Peer baucis-swagger2@0.3.8 wants mongoose@>=3 <5
```

Can we stick to `>=3 <5` ?  

If we choose to do 3 - 4.0.4 we need to do the same on all plugings. And update all of them at the same time whenever a new version of mongoose appear...
