### ISSUE TITLE
http get condition on sub collection

### ISSUE THREAD

**Issue by playUruguay** [wprl/baucis#267]
Hi, i have this model and im trying to get results searching for rols.displayName, 
Any ideas? Thanks
/api/user?select=rols&conditions={ rols.displayName: { "$regex": "' + query + '" } }
<pre>
users:{
    name: "Username",
    rols:[
        {
            displayName: "Name to show"
        }
    ]
}
</pre>

**Comment by wprl** [comment]
Are you getting an error?  It looks like your conditions are not valid JSON, which could be an issue…

**Comment by playUruguay** [comment]
Im trying with a valid json and still doesnt work.
/api/user?conditions={ "rols" : { "displayName" : { "$regex" : "' + query + '" } } }

**Comment by pjmolina** [comment]
Can you paste the real code to review the details?

1. Note that `/api/user?conditions={ "rols" : { "displayName" : { "$regex" : "' + query + '" } } }` is not a valid URL as `+` operator is not available on URLs but only in JS.
2. Note that some symbols needs to be escaped accordingly to URL encoding. `{` `}` etc. See [EncodeUrlComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

A real example working you can try is: [Sample Query](https://model-101.herokuapp.com/api/countries?conditions={%22name%22:{%22$regex%22:%22Ur%22,%22$options%22:%22i%22}}&apikey=icinetic)

**Encoded query**
```
https://model-101.herokuapp.com/api/countries?conditions={%22name%22:{%22$regex%22:%22Ur%22,%22$options%22:%22i%22}}&apikey=icinetic
```

**Decoded query**
```
https://model-101.herokuapp.com/api/countries?count=true&conditions={"name":{"$regex":"Ur","$options":"i"}}
```

This site also helps to do [conversions](http://urldecode.org/).
Regards.
