### ISSUE TITLE
Strict usage of JSON on data response

### ISSUE THREAD

**Issue by pjmolina** [wprl/baucis#271]
If fact, this is an issue for `baucis-json` strictly speaking but posting the issue here as issues in baucis-json are not enabled.

We are using standards baucis queries like  `/api/resource/count=true`
This responds a direct simple value of the row count as expected:
``` 
...other headers...
Content-Type:application/json; charset=utf-8

45
``` 

This is working on JS clients and servers. Tested with NodeJS on server, and AngularJS on client-side both works as expected. The implementations relays on using `JSON.parse()` and `JSON.stringify()` we can parse the serialize the 45 value as a primitive. 

However, accordingly to http://json.org this output is not valid JSON. 
As the spec states: "JSON is build on two structures: a collection or an ordered list of values."

The JSONLint validator report it also as an error. http://jsonlint.com/?json=45

This problems arises when using clients on mobile Apps. We found that well-known deserializing libaries for JSON on Android and iOS reject primitive types as valid JSON.

Therefore, following the principle of been tolerant with the input but strict in the response, I think there is a good reason to consider this a **bug** and generate a response like (A):

``` 
...other headers...
Content-Type:application/json; charset=utf-8

{ "count": 45 }
``` 

or a (B) generic one like:

``` 
...other headers...
Content-Type:application/json; charset=utf-8

{ "value": 45 }
``` 

I know this is problematic as this could break compatibility on working clients, but without strict JSON encapsulation (no simple values allowed) baucis looses interop with other platforms like android and iOS.

I can make a fork of baucis-json and enforce the (B) solution to envelope all single primitive values.
and/or you can make a fix on count method and return something like (A).

What do you think?

**Comment by pjmolina** [comment]
Adde pull request: https://github.com/wprl/baucis-json/pull/1

**Comment by wprl** [comment]
Thank you.  Great PR.  The tests were really helpful.  I fixed a couple bugs and published it as baucis-json-strict.  The current plan is to make it the default in baucis v2.0.0
