### ISSUE TITLE
Registering custom routes on baucis pipeline

### ISSUE THREAD

**Issue by ahmed-negm** [wprl/baucis#272]
Hi,
As in the wiki, baucis middleware applies to all pre-defined API routes.

So, how I could add a new route to the chain?

For example: `galleries/{id}` returns an instance of the gallery,
How I could implement the following route `galleries/{id}/tags` which will do some logic and return a list of tags.

I could implement it using express api like:

``` javascript
controller.get('/tags', function (request, response, next) {
    // Some logic
    next();
});
```

But the problem here is that I should format the response by myself, and I can not utilize the baucis pipeline features like serialization etc.

So is there a way to add, register or hook custom routes to the baucis pipeline chain (not express api)?

**Comment by wprl** [comment]
Thanks for your question!  The supported way to do this is using /galleries/12345?select=tags

**Comment by ahmed-negm** [comment]
Thanks for your reply,

May be I miss a good example, but what I am trying to do is not a query operation, but changing the state of the resource.
For example when I do a POST to this url: `galleries/{galleryId}/addTags/{tagId}`

The semantics here to implement is to link the gallery `{galleryId}` to the tag `{tagId}`. And this is a new route we want to add to baucis and still looking use to the full baucis pipeline: for example to use the serialization pipeline based on previous content negotiation.

**Comment by wprl** [comment]
baucis is geared towards a more resource-oriented approach to URLs  vs. the more RPC-oriented approach you have here. 

So with baucis one would, for example, use PUT at /galleries/12345 with a body of `{ tags: [ "a", "b" ] }` to update the gallery tags. To avoid write conflicts, one would either use optimistic locking or the Update-Operator header field set to $push 

Let me know if you have more questions!
