### ISSUE TITLE
Heterogeneous Content-Type on Error Responses

### ISSUE THREAD

**Issue by pjmolina** [wprl/baucis#273]
Hi. When building the plugin `baucis-swagger2` I found the following issue:

Baucis uses different Content-Types for different kind of errors. 

Samples of current state:
Error `422` for validation errrors returns: `application/json; charset=utf-8`, sample:

```
		[{
			"properties": {
				"type": "required",
				"message": "Path `{PATH}` is required.",
				"path": "age"
			},
			"message": "Path `age` is required.",
			"name": "ValidatorError",
			"kind": "required",
			"path": "age"
		},	
	   ...
		]
```		

However, Error `400` returns `text/html`:

```
		Bad Request: The requested document ID &quot;55118e16a4fbe34804400000xxcv&quot; is not a valid document ID (400).
 ```

Same for `404`: returns `text/html` :  also when asked from the client side with `curl ... -H "Accept: application/json"`

```		
		Not Found: Nothing matched the requested query (404).
```		

For a user, or developer have sense to have `text/html` in some scenarios. But for direct API consumption using `application/json` or `aplication/xml` one expects the errors to follow the same previously negotiated language.

What do you think?
Can we fix errors on baucis to be formatted following the requested Content-Type when possible?

**Comment by wprl** [comment]
Pedro, really like that you've discovered these small loose ends to wrap up!  I think it would be good to bump these to top priority as they can be coded quickly.
