### ISSUE TITLE
Make baucis-json-strict the default for v2.0.0

### ISSUE THREAD

**Issue by wprl** [wprl/baucis#282]
Publish it as baucis-json v2.0.0

**Comment by pjmolina** [comment]
+1

**Comment by wprl** [comment]
@pjmolina Fyi you can use baucis-json-strict now, when using v1.x of baucis.  That's probably obvious, but thought I might as well mention it.

**Comment by pjmolina** [comment]
Superb! :-) thanks for it. 
We will benefict from it asap!

-----Mensaje original-----
De: "William P. Riley-Land" <notifications@github.com>
Enviado: ‎03/‎07/‎2015 19:47
Para: "wprl/baucis" <baucis@noreply.github.com>
CC: "Pedro J. Molina" <pjmolina@gmail.com>
Asunto: Re: [baucis] Make baucis-json-strict the default for v2.0.0 (#282)

@pjmolina Fyi you can use baucis-json-strict now, when using v1.x of baucis. That's probably obvious, but thought I might as well mention it.
