### ISSUE TITLE
Server does never send 304

### ISSUE THREAD

**Issue by henning96** [wprl/baucis#290]
Why does baucis not send an 304 status code when the etag in my request header 'If-None-Match' is equal to the etag that I've received the last time I've send an GET request to the server. How is caching meant to be implemented when the server does never send an 304 statusCode?
How can I add this functionality?

**Comment by pjmolina** [comment]
Hi. `If-None-Match` works as expected for me in baucis.

See this working example:

```
curl -k -i "https://an-dark-tabarca-6169.herokuapp.com/api/customers?limit=20&skip=40&apikey=icinetic" -H "If-None-Match: W/\"2-11FxOYiYfpMxmANj4kGJzg\""
```

However I have this running on Heroku, but not in Bluemix. It is a reported error on the infrastructure of Bluemix itselft. See this (issue)[https://developer.ibm.com/answers/questions/203063/recurrent-intermittent-502-errors-bad-gateway-on-b-1.html].

Do you have any middleware/web server/router/proxy running on the top of your server?
Take a look to the headers to look for clues.

**Comment by henning96** [comment]
Thanks for your response. I've found out something interesting: I've only tested this with queries for a specific id like "projects/55c72f0dfd0ba83e1cc9c0d0". This did not work...
But when I query for this project using a querstion mark: projects?conditions={"id": "55c72f0dfd0ba83e1cc9c0d0"} it works! The server returns 304.
This seems to me like a bug... Also the returned etag has a different structure. The first query returns the etag: "0875e3e20b00792ae6d4da1fd344dbbb" and the second one returns: W/"2-11FxOYiYfpMxmANj4kGJzg". But both etags should be the same...

**Comment by henning96** [comment]
Sorry, ofcourse they are note exactly the same (the first one is an object and the second one is an array). But nevertheless using the etag "0875e3e20b00792ae6d4da1fd344dbbb" in If-None-Match when querying for a specific id "projects/55c72f0dfd0ba83e1cc9c0d0" does NOT return 304...

**Comment by wprl** [comment]
This turned out to be an issue with Bluemix and/or Node and/or Express.  See: 
 - https://github.com/nodejs/node/issues/2842
 - https://github.com/strongloop/express/issues/2749
