### ISSUE TITLE
Request stalled indefinitely, results ERR_EMPTY_RESPONSE in Chrome

### ISSUE THREAD

**Issue by voodooattack** [wprl/baucis#291]
When I POST to a collection, the request never returns if a validation error occurs. It takes approximately 2 minutes for chrome to return with ERR_EMPTY_RESPONSE, and the server sends nothing. (not even headers)

I really can't isolate the problem, is this happening to anyone else?

**Comment by pjmolina** [comment]
No. Not happening for me: Baucis works for me by default. :-) 
Did you added any express middleware or any hook code? 
Can you share a sample POST with full body and and headers to try to help you?

**Comment by voodooattack** [comment]
I've reduced it to the bare bones:

```
let config = JSON.parse(fs.readFileSync('site_config.json', 'utf8'));
db.connect(config.database.uri, config.database.options);

let models = require('models')(db, config);
let app = express();

let controllers = {};

for(var model in models)
  if (models.hasOwnProperty(model))
    controllers[model] = baucis.rest(models[model]);

controllers.User.select(
  '-salt -hash -loginAttempts -lastLoginAttempt -provider -providerId -providerData'
);

app.set('controllers', controllers);
app.use('/api', baucis());
```
This is what it looks like (no response at all):
![]
(https://dl.dropboxusercontent.com/u/27714141/baucis.png)

**Comment by pjmolina** [comment]
Error in line 68 is a mongoose error (ORM persistence in mongoDb). Do you have the details of the error? 
It looks like a validation error based on the data provided with respect to the model used. Double check the data you are sending in the post:

1. It is compliant with the model.
2. No required field in the model is missing in the data.

**Comment by voodooattack** [comment]
Yes, I'm POSTing with an existing email. The problem is that baucis is not responding with an error when the validation fails.

**Comment by pjmolina** [comment]
I see. Seems like a bug in baucis then. Let's see what @wprl can tell us about it!

**Comment by wprl** [comment]
Which version are you using?

**Comment by Toolito** [comment]
Same issue here, version 1.6.0
And mongoose v4.1.1

**Comment by voodooattack** [comment]
1.6.0 here as well.
