### ISSUE TITLE
PrototypeOf RestError object should be RestError

### ISSUE THREAD

**Issue by Toolito** [wprl/baucis#293]
https://github.com/wprl/baucis/blob/master/Controller/errors.js#L89

In this protect.use function, error is an instance of Error, not RestError.
This causes 500 internal server errors, when error is not caught by converters, and it prevents me to use custom errors.

<img width="605" alt="capture d ecran 2015-08-24 a 15 25 02" src="https://cloud.githubusercontent.com/assets/1357929/9441097/59232338-4a74-11e5-82b0-9e82f738f1bc.png">

![response](https://cloud.githubusercontent.com/assets/1357929/9441071/24326f9e-4a74-11e5-83ac-0dc5e5680fad.png)

**Comment by wprl** [comment]
Thanks for reporting this.  Do tests pass for you?  I haven't been able to reproduce this…

**Comment by Toolito** [comment]
It works since you updated rest-error package with new errors.

https://github.com/wprl/rest-error/commit/ad86409c15f32b01226b25c62df28714c0cf490d
https://github.com/wprl/rest-error/commit/f6e56f028a779589647ed3b615c375215814ed1a

Thanks
