### ISSUE TITLE
has no method 'lastModified'

### ISSUE THREAD

**Issue by ztripez** [wprl/baucis#297]
I load my models and connection  from a private module (the module is shared between differnt projects (like workers and such).

This is very much test-code.
router module:
```
router.use(function (req, res, next) {
	var userController = require("../controller/UserController")(req.db);
	req.app.all(baucis());
	next();
})
```

UserController
```
var baucis = require('baucis');
module.exports = function (conn){
	var controller =  baucis.rest(conn.model.User);
	return controller;
}
```

This results in 
```
TypeError: Object function model(doc, fields, skipId) {
    if (!(this instanceof model))
      return new model(doc, fields, skipId);
    Model.call(this, doc, fields, skipId);
  } has no method 'lastModified'

```

**Comment by ztripez** [comment]
I was able to find the problem by myself. 
If you you load models (and schemas) from mongoose from a submodule the instancing get messed up. I had to add baucis to my submodule export it and use that in my application instead. 
Not the most pretty solution but it works.

**Comment by wprl** [comment]
Would you mind giving a code example of how you solved this?

**Comment by ztripez** [comment]
if you check https://github.com/wprl/baucis/issues/298 you can se how i did it in the database module.

Here is tldr:
database-module.js

           // Other db stuff.

           module.exports.baucis = request('baucis');


main app.js

            var db = reqiure('database-module');
            db.baucis.rest(db.model.User);


This is before i learned about peer dependencies and haven't had the time tried to changed in the database module, but it works.

**Comment by wprl** [comment]
OK now I understand.  I think this would be solved by using peerDependencies, as you hinted at.  Let me know if it causes you any more issues.
