### ISSUE TITLE
skip and limit parameters seems to be converted to strings

### ISSUE THREAD

**Issue by swfredrik** [wprl/baucis#303]
Internal Server Error","message":"Failed to parse: { find: \"devices\", filter: {}, sort: { _createdAt: -1 }, skip: \"2\" }. 'skip' field must be numeric. (500).","stack":"MongoError: Failed to parse: { find: \"devices\", filter: {}, sort: { _createdAt: -1 }, skip: \"2\" }. 'skip' field must be numeric.\n 

HttpRequest: curl 'http://localhost:3000/api/devices?skip=2&sort=-_createdAt'

Baucis version 1.6.3

**Comment by sascha1337** [comment]
dude will u fix this ? its not difficult

**Comment by wprl** [comment]
Happy to check out a pr

**Comment by kbailey4444** [comment]
@swfredrik Do you get the same error if you explicitly make the skip field a string? Try this:
```
curl 'http://localhost:3000/api/devices?skip="2"&sort=-_createdAt'
```

Also, what version of MongoDB do you have?

**Comment by wprl** [comment]
FYI There's a $50 bounty for closing this issue on Bountysource.

**Comment by pjmolina** [comment]
Looks directly related to this mongoose bug [#3763 limit and skip doesn't work on mongodb 3.2 ](https://github.com/Automattic/mongoose/issues/3763).

**Comment by wprl** [comment]
Thanks @pjmolina.  Published as v1.6.4

**Comment by wprl** [comment]
@pjmolina.  Be sure to go here to collect the $50 bounty: https://www.bountysource.com/issues/29532280-skip-and-limit-parameters-seems-to-be-converted-to-strings

**Comment by omererbil** [comment]
if u want pass a variable on skip or limit just do this
var i=Number(req.query.name)
.skip(i)
