### ISSUE TITLE
$slice queries in Baucis

### ISSUE THREAD

**Issue by msravi16** [wprl/baucis#309]
Hi Team,
I am storing object Ids in an array. I want to paginate the values in array. Paginating array can be done using $slice.
Is there any way to execute baucis webservice using $slice keyword.
I tried to add $slice query in the conditions it dint work.  
http://localhost:3000/rest/api/box?conditions={"_id":"574836f7eb5c739507ebceb7","users":"{$slice:[0,5]}"}

Could you please let me know if it is implemented.
For more information on $slice http://www.hacksparrow.com/mongodb-pagination-using-slice.html

**Comment by wprl** [comment]
Looks like an issue with malformed JSON. Try this instead:

`"users": { "$slice": [0,5] }`

If that doesn't help please post the error message you are receiving :)

**Comment by msravi16** [comment]
Hi Wprl,
You are right. There was problem in URL. I corrected it, below is the url 
http://localhost:3000/rest/api/box?conditions={"_id":"574836f7eb5c739507ebceb7","questions":{"$slice":"[0,5]"}}

After correcting the URL I get the below error.

status: 500,
name: "Internal Server Error",
message: "Cast to ObjectId failed for value "{$slice:[0,5]}" at path "questions" (500).",
stack: "CastError: Cast to ObjectId failed for value "{$slice:[0,5]}" at path "questions" at MongooseError.CastError (

My questions field contains array of ObjectIds. 
I applied the same query for array of strings, it is returning the blank array. In below url photos is the array of strings.
http://localhost:3000/rest/api/tests?conditions={"_id":"574430b5baf4d996598cb5ac","photos":"{$slice:[0,5]}"}

**Comment by wprl** [comment]
Conditions needs to be valid JSON.  Like so:  `http://localhost:3000/rest/api/tests?conditions={"_id":"574430b5baf4d996598cb5ac","photos":{"$slice":[0,5]}}
