### ISSUE TITLE
PUT using different field (not _id)

### ISSUE THREAD

**Issue by bradwbradw** [wprl/baucis#310]
Is there a way to configure baucis to use a different property name when updating a document?

For example, I have an object "car" with a field `number` that is unique.  I would like to send a PUT to `car/13` instead of using the mongoID, as in `car/571e68f3fdfd1429004c51cb`.

Then the update would affect the "car" that has `number:13`

I would also be OK with using a method that looks like "update all objects that satisfy {conditions}"

but it looks like out-of-the-box, baucis only supports updating a single instance by its mongoId

**Comment by wprl** [comment]
Hi Brad, thanks for your question.  This feature is available using the `findBy` controller method.  Here is more info from the Wiki: https://github.com/wprl/baucis/wiki/Controllers#controllerfindby

**Comment by bradwbradw** [comment]
works greeat, thanks
