### ISSUE TITLE
Singular on subresource endpoint

### ISSUE THREAD

**Issue by hoangzinh** [wprl/baucis#313]
Hi Team,

Suppose, I have 2 identities:
- User
- Profile
A User has one Profile.

I'm concerning
- Create an endpoint to Profile like: /users/:userId/profile, just singular form.
- Prevent CRUD access to /profiles

Does Baucis allow me do it? Or It's invalid with restful API principle, I read some article, they said that we should prefer plural form.

**Comment by wprl** [comment]
Hi @hoangzinh, thanks for using Baucis.  

To change the name used in the URL, use https://github.com/wprl/baucis/wiki/Controllers#controllerfragment 

To create subcontrollers, take a look at https://github.com/wprl/baucis-vivify If it doesn't suit your use case, you may need to fork it and modify it to as needed.

Feel free to reopen this, or create a new issue if you have other questions.

Cheers,
William
