### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by tom-heyvaert** [wprl/baucis#315]
Hello, 

I am doing a visualization on some sensordata. My data has the following structure and contains hundreds of thousands records:

```
/* 2 */
{
    "_id" : ObjectId("58b5478b03b3712ed89f62cd"),
    "timestamp" : "2016-12-14T18:39:51.245Z",
    "beaconId" : "Kitchen-Microwave",
    "rssi" : "-81",
    "temperature" : "21.625",
    "moving" : "false",
    "orientation" : "VERTICAL_UPSIDE_DOWN",
    "x" : "500.0",
    "y" : "-875.0",
    "z" : "0.0",
    "maxRssiBeacon" : "Kitchen-Microwave",
    "activity" : "Cooking"
}

/* 3 */
{
    "_id" : ObjectId("58b5478b03b3712ed89f62ce"),
    "timestamp" : "2016-12-14T18:39:51.245Z",
    "beaconId" : "Bathroom-Shelf",
    "rssi" : "-96",
    "temperature" : "21.375",
    "moving" : "false",
    "orientation" : "LEFT_SIDE",
    "x" : "703.125",
    "y" : "765.625",
    "z" : "-15.625",
    "maxRssiBeacon" : "Kitchen-Microwave",
    "activity" : "Cooking"
}
```

I am visualization data from all the sensors between a time interval with following query:
`../api/beacons?conditions={"timestamp" : { "$gte" : "' + startISOdate + '", "$lte" : "' + endISOdate+'"}}`

This works great but it's obvious when I chose a large interval the amount of records is overwhelming. This brings me to my question. I would like to sample the data but I'm not sure how to tackle this or if it's even possible with Baucis. I figured I would need to use some aggregate function.

The idea would be to group them by beaconId then take the average of X amount of records for the values I have. 

Thanks in advance

**Comment by wprl** [comment]
Hi, Tom.  Good question.

In MongoDB after 3.2, this can be accomplished with the $sample aggregation stage.  The current release of baucis (1.x) isn't compatible with the aggregation pipeline, however.  

There are other ways to achieve a random sample, required for MongoDB before 3.2 but still compatible with later MongoDB releases.  Some of these approaches are outlined on the StackOverflow question: http://stackoverflow.com/questions/2824157/random-record-from-mongodb

If one of these solutions fits your project and you need any help getting it working with Baucis, please comment here and we can reopen the ticket.

Cheers,
William
