### ISSUE TITLE
conditions not working with keys with upper case letters

### ISSUE THREAD

**Issue by bodo22** [wprl/baucis#316]
eg the query 
    `localhost:3002/api/actions?conditions={virtualdevice:number}`

returns the expected dataset, but if the key (here virtualdevice) contains an upper case letter, the condition is ignored and all datasets are return, eg
    `localhost:3002/api/actions?conditions={virtualDevice:number}`

in my mongodb it works fine with the .find() feature.

**Comment by pjmolina** [comment]
As far as I know, this is the expected behaivour. 
Search by fields is case-sensitive in baucis and mongoose (the underlying ORM). If the property is defined as `virtualdevice` you must use it as it is. If case is changed, then: no matching field is found, it is removed from conditions, and therefore, all documents in collection returned.

**Comment by bodo22** [comment]
i did not clarify clearly, sorry.

The keyname was originally `virtualDevice` in the DB. conditioning by this key was disregarded, returning the whole dataset. After changing the key to `virtualdevice` to find out if the problem lies within the case sensitivity, the expected dataset was returned. As nothing else was changed, conditioning by other lower-case keys worked in both cases and filtering in the find() method in the mongodb console works, I suspect it has something to do with baucis or mongoose.

**Comment by bodo22** [comment]
sorry again. found the error, has to do with objectIds being parsed as strings, not as objects. My fault.

**Comment by wprl** [comment]
@bodo22 glad you discovered the issue and don't be sorry.  Feel free to ask any questions you have in the future.
