### ISSUE TITLE
Question: Is it possible to overwrite the body on the swagger definition for an endpoint?

### ISSUE THREAD

**Issue by jomaora** [wprl/baucis#318]
Hey!

We're using baucis to generate the swagger documentation for all our models. However we have some other endpoints that are not related to any mongoose schema. We found a trick to add this kind of endpoints.

First, we create an empty mongoose schema for the endpoints that are not related to schemas. We use the endpoint property in the baucis definition to identify which endpoints are not related to schemas, the other, of course, they have the model property. For instance, these are two definition for one endpoint with schema and one without.

```js
module.exports.baucis = {
    model: 'discipline',
    disableMethods: 'post delete put'
};
```

```js
module.exports.baucis = {
    endPoint: 'progressions',
    disableMethods: 'get post delete put',
    apis: [
        {
            path: '/progressions',
            operations: [
                {
                    httpMethod: 'POST',
                    parameters: [
                        {
                          paramType: 'body',
                          name: 'document',
                          description: 'type',
                          required: true,
                          dataType: 'object'
                       }
                    ]
                }
            ]
        }
    ]
};
```
As you can see for the endpoint not related to a mongoose schema,  we disable all the http operators and we just add our custom apis. This allow us to have this:

<img width="967" alt="capture d ecran 2017-05-16 a 11 17 29" src="https://cloud.githubusercontent.com/assets/7602475/26098837/4b5b580a-3a29-11e7-9868-ca36222b6baf.png">

It works. However, we would like to have more details to explain the structure of the body for the POST on the non related to a schema endpoint /progressions. Docs says that to describe body parameters, the property dataType should be use. But I just can set 'object'. 

Is it possible to set a schema as you can do it in a basic swagger definition?

I have already tried to add the schema property, like this

```js
    apis: [
        {
            path: '/progressions',
            operations: [
                {
                    httpMethod: 'POST',
                    parameters: [
                        {
                          paramType: 'body',
                          name: 'document',
                          description: 'type',
                          required: true,
                          schema: {
                            type: 'object',
                            properties: {
                              content_id: {
                                type: 'string'
                              }
                            }
                          }
                        }
                     ]
               }
           ]
        }
    ]
```

without any success. I also tried to create a mongoose schema and to set it on dataType property, like this:

```js
    apis: [
        {
            path: '/progressions',
            operations: [
                {
                    httpMethod: 'POST',
                    parameters: [
                        {
                          paramType: 'body',
                          name: 'document',
                          description: 'type',
                          required: true,
                          dataType: new mongoose.Schema({
                            content_id:  String
                          })
                        }
                     ]
                }
             ]
        }
    ]
```

So here's my question, is there any way to overwrite the body model definition on baucis?

**Comment by pjmolina** [comment]
Hi. 
You are using Swagger 1.1, right?
Note the current version of Swagger (now renamed to [OpenAPI](https://www.openapis.org/)) is Swagger 2.0. 
And the following one v. 3.0 is approaching.

Depending on the version you are targeting I recommend different plugins:

- swagger v1.1 [baucis-swagger](https://www.npmjs.com/package/baucis-swagger)
- swagger/openapi v2 [baucis-swagger2](https://www.npmjs.com/package/baucis-swagger2)
- openapi v3 [baucis-openapi3](https://www.npmjs.com/package/baucis-openapi3)

In any case, plugins for swagger/openapi generation over baucis use reflection over controllers to generate the Swagger spec as a JSON document.

Once generated, you can fine tune it to add content, or remove it to totally tailor it to your needs.
