### ISSUE TITLE
Change Unprocessable Entity Error response Body

### ISSUE THREAD

**Issue by bodo22** [wprl/baucis#319]
I have an express server working together with baucis and have been struggeling to get and change the response body when an unprocessable entity error occures. After testing, my understanding is that baucis.outgoing is not called when an error occures. 

Am i right in thinking that these lines:

``` javascript
var f = formatter(error instanceof RestError.UnprocessableEntity);
f.on('error', next);

es.readArray(errors).pipe(f).pipe(response);
```
from `Controller/errors.js` are piping the response out the door, preventing further manipulating (eg. with baucis or express)?

How would it be possible to handle this responses body?

**Comment by wprl** [comment]
Thanks for your question.  For custom handling of errors, [turn off the built in error handling](https://github.com/wprl/baucis/wiki/Controllers#controllerhandleerrors) for the controller and/or add Express handling middleware.  Going to close but feel free to ask any additional questions that may come up.

**Comment by bodo22** [comment]
Thanks, I hadn't noticed that option! 
The Problem is that when a post or put request is made and a 422 error is thrown, this option doesn't seem to strip the response body. the body I am getting looks something like this:

```
[
  {
    "stack": "ValidatorError: Path `pathname` is required. *really long stack trace*",
    "message": "Path `pathname` is required.",
    "name": "ValidatorError",
    "properties": {
      "type": "required",
      "message": "Path `{PATHNAME}` is required.",
      "path": "pathname"
    },
    "kind": "required",
    "path": "pathname"
  }
]
```

**Comment by wprl** [comment]
Sounds like you should add an Express error handler to your app https://expressjs.com/en/guide/error-handling.html

That will allow you to alter the error response before it is sent.

**Comment by bodo22** [comment]
I wasn't reading the wiki properly, just noticed and corrected a typo there. Before it said `emptyCollection(false)`, should be correct now `handleErrors(false)` :)

**Comment by wprl** [comment]
Thank you!  

William Riley-Land / Open Source Consultant
william@kun.io / +1.573.823.6440
Kun.io Labs LLC
http://kun.io
