### ISSUE TITLE
Etag Header without chunked encoding

### ISSUE THREAD

**Issue by ivanhuay** [wprl/baucis#321]
I had a problem running an application made with baucis in [flynn](https://github.com/flynn/flynn).

When there is no record created and baucis sends the answer an error occurs with the headers and flynn response 'Service Unavailable'.

i make an issue in flynn [#4157](https://github.com/flynn/flynn/issues/4157) and they help me to find the problem with headers. But i cant remove Trailer header or enable chunked encoding in baucis.

**Comment by pjmolina** [comment]
Hi. 
_deja-vù_ I had a similar issue on IBM Bluemix + Baucis on 2015. 

Flynn uses go under the hood, right?

See this [thread for full history](https://developer.ibm.com/answers/questions/203063/recurrent-intermittent-502-errors-bad-gateway-on-b-1/).

In summary: 

1. The HTTP spec about trailers is a bit ambiguous, or at least, leave some aspect open to interpretation.
2. NodeJS implements trailers in his HTTP stack in one way.
3. Go language implements trailers in another way.
4. Talking clients (Node) to servers (in Go) (or with middleware in Go: like routers) **fails**.

We (with the help of @wprl ) discovered this on July/2015 and looks **to be unsolved two years later**.  :-(

Note that this is not a bug in baucis, but a lack of consensus about NodeJS developers vs Go developers about how things should work with Trailers. It could be a bug in a strict sense in NodeJS but other could argue Go is too strict at this point.

See the case opened on [ExpressJS about this](https://github.com/expressjs/express/issues/2749?cm_mc_uid=91220535827514987640651&cm_mc_sid_50200000=1498764065) and [this one](https://github.com/expressjs/express/issues/2750?cm_mc_uid=91220535827514987640651&cm_mc_sid_50200000=1498764065).

In my case, to be pragmatical, I had to skip Bluemix and moved to Heroku to have the app running.

Sorry, no workaround available to my knowledge, so far.

**Comment by pjmolina** [comment]
The progress of the [issue in the NodeJS codebase](https://github.com/nodejs/node/issues/2842).

**Comment by ivanhuay** [comment]
Thank you very much for the information

I will continue to investigate alternatives for Paas platform.

Do not imagine that the problem was foundational with go.
