### ISSUE TITLE
é character in mongo database turns into Ã© in json

### ISSUE THREAD

**Issue by bradwbradw** [wprl/baucis#325]
here's a screenshot of a document i have, using robomongo "view document" dialog
![screen shot 2017-08-10 at 11 08 57 am](https://user-images.githubusercontent.com/4715252/29184979-bdcb783a-7dbc-11e7-9532-0c034a830b2c.png)

the resulting JSON from baucis-provided GET request is as such:
![screen shot 2017-08-10 at 11 13 33 am](https://user-images.githubusercontent.com/4715252/29185085-0e644416-7dbd-11e7-8277-a9da69bfd17c.png)

I'd expect the JSON to be encoded such that it respects characters encoded in standard unicode found in the mongo db, as in:
```
"name": "rosé wine recommendations"
```

versions:
```
    "baucis": "1.6.5",
    "baucis-decorators": "1.0.3",
    "baucis-swagger": "1.1.2",
```
```
mongo
MongoDB shell version: 3.2.11
```

**Comment by pjmolina** [comment]
Can you discard this is not an issue in your browser-plugin-viewer for JSON?

As far as I know, it should be transported all the time as UTF-8 end-to-end preserving the unicode chars.
I worked intensively with baucis + mongodb an the Spanish language sending chars like: `¿¡áéíóúüñÁËÏÓÚÜÑ`  and never found any issue like this.

**Comment by bradwbradw** [comment]
when using Postman, i can see `é`, which indicates it's not a bug in baucis. thanks @pjmolina 

sadly, it is a bug in the JSON Formatter chrome plugin (v0.6.0)
