### ISSUE TITLE
API endpoints hanging/not loading after updating NodeJS

### ISSUE THREAD

**Issue by jjfattz** [wprl/baucis#328]
I have a simple API, based off the examples in the documentation.  Everything was working fine until I updated my NodeJS (and all packages) to the latest stable release.  I updated NodeJS from 6.10 to 8.6.  I have latest version of Baucis.  Now my API endpoints (i.e. **/api/vendors**) do not load.  The connection just hangs until it times out without errors.

I can confirm that the requests are being received, as I can see logs from the middleware IP filter I created; logs are showing when requests are made.  I can also see that the **/api/documentation** works for the swagger middleware I am using.  It responds with all the proper JSON data.  I have also confirmed successful connection to the Mongo DB (version 3.4.2) and the data is all still there.

Here is a basic example of how I am implementing this simple API:
`
var express = require('express');
var mongoose = require('mongoose');
var baucis = require('baucis');
var swagger = require('baucis-swagger');
var database = require('./database');
var ipfilter = require('./ipfilter');

var port = 3333;

var app = express();

var db = mongoose.createConnection(database.connection_string);

var Vendor = new mongoose.Schema({
    vendor_id: String,
    company_name: String,
    street_address: String,
    city: String,
    state: String,
    country: String,
    postal: String,
    phone: String,
    email: String
});

var model = db.model('vendor', Vendor);

var vendorController = baucis.rest(model);
vendorController.request(ipfilter.localOnly); // I have removed this middleware, no change

app.use('/api', baucis());
app.use('/docs', express.static('swagger-ui/'));
app.listen(port);
console.log('API server listening on port '+port+'...');

// app.on('uncaughtException', function (error) {
//    console.log(error);
// });
`

Any help, ideas, or direction would be greatly appreciated.

Thanks!

**Comment by pjmolina** [comment]
Hi @jjfattz 
I just tried to [reproduced your sample](https://gist.github.com/pjmolina/5b94fdaebf8aa8ee8ad97af3647d77a0).

I tested it under the following environments: 

- windows 10 + NodeJS 8.4.0, and then
- windows 10 + NodeJS 8.6.0

In both cases I was able to access the API without problems. (I was unable to repro your problem):

- create vendor:  `curl -i -X POST -H "Content-Type: application/json" --data "{\"vendor_id\":\"a\"}" http://localhost:3333/api/vendors` 
- query vendors:  `curl http://localhost:3333/api/vendors`

**Comment by jjfattz** [comment]
Hi @pjmolina 

Thanks for taking a look at it and testing it out.  Good to know that its working for you.

It must be something on my setup.  I am running on MacOS Sierra 10.12.6.

I will keep digging.

Thanks

**Comment by jjfattz** [comment]
Ok, so I ended up deleting the node_modules directory and cleared out the dependencies in my package.json file.  Then, I re-installed all packages (i.e. **npm install --save baucis**) one at a time, and that has fixed my issue.

Thanks!
