### ISSUE TITLE
deco dependency is outdated

### ISSUE THREAD

**Issue by ivanhuay** [wprl/baucis#333]
in package.json: `"deco": "^0.12.0",`

[current version](https://github.com/wprl/deco): 2.0.2 

the previous version is not even documented

**Comment by wprl** [comment]
Thanks, happy to accept a PR for this.

**Comment by wprl** [comment]
Any interest in becoming a maintainer @ivanhuay ?

**Comment by ivanhuay** [comment]
yes I'm interested I'm going to send a pr of this :smile:
