### ISSUE TITLE
Add support for the JSON API format

### ISSUE THREAD

**Issue by canac** [wprl/baucis#98]
It would be awesome if there were an option to send and receive data in the [JSON API format](http://jsonapi.org). The main and possibly only difference would be that all requests and responses would have a root element. For example, a request to `/api/users` would return

```
{
    "users": [{
        "user_id": 1,
        "user_name": "Someone"
    }, {
        "user_id": 2,
        "user_name": "Someone else"
    }]
}
```

instead of

```
[{
    "user_id": 1,
    "user_name": "Someone"
}, {
    "user_id": 2,
    "user_name": "Someone else"
}]
```

My use case for this is getting baucis to work out of the box with Ember Data, which expects data to be in the JSON API format. Is there any chance of getting this feature implemented?

**Comment by mikberg** [comment]
Is this still possible? Can't find an easy way to alter the representation of collections.

**Comment by wprl** [comment]
@mikberg Is what still possible?

**Comment by mikberg** [comment]
Wrapping the response array in an object, e.g. `{ users: [ ... ] }`. Is this still possible, after the document stage of middleware has been deprecated? It's not obvious to me how to achieve this with decorators or streams, or if it's even possible.

**Comment by wprl** [comment]
I don't think that is possible without modifying baucis-json.  I'll add a ticket over there.

**Comment by wprl** [comment]
On second thought I'll go ahead and reopen here.

**Comment by Ghostavio** [comment]
anything new on this?

**Comment by wprl** [comment]
Do in conjunction with #260

**Comment by wprl** [comment]
Dropping in favor of HAL for Baucis2, unless there are objections.
